### ISSUE TITLE
Issue with dfu prog on F767

### ISSUE THREAD

**Issue by rusefillc** [STMicroelectronics/STM32Cube_MCU_Overall_Offer#11]
It looks like stm32cube programmer  does not erase proper page 12/erases non existent page 8 in some corner case of dual bank

I'm having a problem with STM32CubeProgrammer and a 1MB STM32F767ZG configured in dual bank mode. On the left, I tried to flash a 520k bin to the device, over the top of previous firmware.

 

Expected behavior: erase sectors 0-7, 12, then write 520K bytes starting at address 0x08000000.

 

Actual behavior: erases sectors 0-8, then write 520K bytes starting at address 0x08000000.

 

Since it tries to erase the non-existent sector 8, sector 12 (the actual sector at 0x08080000) doesn't get erased and as such the contents of sector 12 get corrupted by the multiple writes without an erase.

 

See screenshot below: stm32cubeprogrammer tries to erase sector 8 at 0x0808 0000, but in dual bank mode, there is no sector 8!

![image](https://user-images.githubusercontent.com/48498823/144929764-d93993d7-508d-4145-9af8-ffc482a8f02d.png)

See https://community.st.com/s/question/0D53W00001EEBXXSA5/stm32cubeprogrammer-incorrectly-erases-on-dual-bank-1mb-stm32f7

**Comment by PierreLeCorre** [comment]
Dear @rusefillc , thanks to transmit this information. Unfortunately, this issue is not related to the content of this repository and so i closed it.

For your information, i have also transmitted your issue to our development team with the internal reference 120183.

**Comment by rusefillc** [comment]
@PierreLeCorre is there a more relevant github repo for this issue? What's the best way to check on internal ticket 120183 going forward?

**Comment by PierreLeCorre** [comment]
@rusefillc We don't provide access to our internal bug tracking system and we don't provide GitHub repository for the STM32CubeProgrammer where you can submit issues. Then, you have taken the correct path to submit your issue on  https://community.st.com.

**Comment by rusefillc** [comment]
@PierreLeCorre this did not make into 2.10 update recently, do you know if there is hope for 2.11?

**Comment by rusefillc** [comment]
fresh screenshot of 2.12

![image](https://user-images.githubusercontent.com/48498823/215497271-794241ec-4b8f-4608-84bf-5b0cba5779ea.png)

**Comment by ALABSTM** [comment]
ST Internal Reference: 120183
