### ISSUE TITLE
Repo "stm32-w25q80ew" listed in misc components does not exist

### ISSUE THREAD

**Issue by pavel-a** [STMicroelectronics/STM32Cube_MCU_Overall_Offer#24]
https://github.com/STMicroelectronics/stm32-w25q80ew -> not found

https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/blob/c108cb39c09ee71c0786fb2710e67b0205af97d9/README.md?plain=1#L470

**Comment by TOUNSTM** [comment]
Hello @pavel-a,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With regards,

**Comment by ALABSTM** [comment]
Hi @pavel-a,

Thank you for having drawn our attention on this. Indeed, the mentioned repo does not exist. Hence, the corresponding line has been removed from the list.

With regards,

**Comment by ALABSTM** [comment]
Fixed in 6800bbd79bb14d3f010a684ff58c3cb09a700745
