### ISSUE TITLE
Today is the year of 2024. STM32CubeProgrammer fails to report correct flash size of STM32F767ZG

### ISSUE THREAD

**Issue by rusefillc** [STMicroelectronics/STM32Cube_MCU_Overall_Offer#35]
My photo is not amazing but ZG is pretty visible  - part of STM32F767ZGT6

![WhatsApp Image 2024-07-30 at 12 06 08_7ece3afa](https://github.com/user-attachments/assets/54b88e83-e812-4ee6-997d-b8071f48694d)

expected: tools report 1Mb flash
actual result: tools report 2Mb

```
  12:06:56 : STM32CubeProgrammer API v2.17.0 | Windows-64Bits 
  12:07:04 : UR connection mode is defined with the HWrst reset mode
  12:07:05 : USB speed   : Full Speed (12MBit/s)
  12:07:05 : Manuf. ID   : STMicroelectronics
  12:07:05 : Product ID  : STM32  BOOTLOADER
  12:07:05 : SN          : 20663077464B
  12:07:05 : DFU protocol: 1.1
  12:07:05 : Board       : --
  12:07:05 : Device ID   : 0x0451
  12:07:05 : UPLOADING OPTION BYTES DATA ...
  12:07:05 :   Bank          : 0x00
  12:07:05 :   Address       : 0x1fff0000
  12:07:05 :   Size          : 44 Bytes
```

![image](https://github.com/user-attachments/assets/cb876e14-a3b9-4a1b-af20-e61f2b1176a4)

**Comment by ALABSTM** [comment]
Hi @rusefillc,

Thank you for this other report. However, as already said [here](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/issues/11#issuecomment-1004105398), this support channel is mainly dedicated to provide support on firmware items published **within** [this](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer?tab=readme-ov-file#content) list of repositories.

Other support requests like yours, related to the ecosystem and tools, should be submitted to the **_ST Community_**, as already said [here](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/issues/11#issuecomment-1004184039). Issues related to the **_STM32CubeProgrammer_** should be submitted in [this](https://community.st.com/t5/stm32cubeprogrammer-mcus/bd-p/stm32-mcu-cubeprogrammer-forum) forum.

Please allow me to close this issue. Thank you for your comprehension.

With regards,
