### ISSUE TITLE
STM32_Programmer_CLI.exe output as JSON

### ISSUE THREAD

**Issue by ckrenslehner** [STMicroelectronics/STM32Cube_MCU_Overall_Offer#41]
Hi! 

I wanted to open a discussion for this, but this did not work.

I wanted to ask the following: Is it possible to get the output of STM32_Programmer_CLI.exe as JSON?
We use the CLI within one of our internal software tools and the parsing of the output is a little brittle. A structured output format would help. 

Thanks, 
Christian

**Comment by ALABSTM** [comment]
Hi @ckrenslehner,

Thank you for your question. I suggest that you submit it to the **ST Community**, precisely on the [STM32CubeProgrammer (MCUs)](https://community.st.com/t5/stm32cubeprogrammer-mcus/bd-p/stm32-mcu-cubeprogrammer-forum) forum. You should find there a more specific support and the answers you are looking for.

Please allow me to close this issue. Thank you for your comprehension and good luck.

With regards,
